-
  name: Check connectivity to target servers
  hosts: target1
  become: yes
  tasks:
    - include_vars: variables.yml

    - name: Install EPEL Repo
      yum: name=epel-release state=present

    - name: Install FirewallD
      yum: name=firewalld state=present

    - name: start FirewallD service
      ansible.builtin.systemd: name=firewalld state=started enabled=yes


    - name: Install MariaDB
      yum: name = {{ item }} state=present
      with_items:
        - mariadb-server
        - mariadb-client
     
    
    - name: Start MariaDB service
      service:
        name: mariadb
        state: started
        enabled: yes

    - name: Install all required dependencies
      yum: 
        name:
          - MySQL-python
          - python3-PyMySQL
          - python3
          - git
          - python-pip
        state: present

    - name: Create Database
      mysql_db:
        name: ecomdb
     
    - name: Create Database User        
      mysql_user:  
        name: ecomuser
        password: "{{ pw_db }}"
        priv: '*.*:ALL'
        state: present
        host: localhost

    - name: Deploy and configure web
      yum:
        name:
          - httpd
          - php
          - php-mysql
        state: present 

    - name: Download repository from Github. 
      git:
        repo: https://github.com/kodekloudhub/learning-app-ecommerce.git
        dest: /var/www/html

    - name: Start HTTP service
      service:
        name: httpd
        state: started
        enabled: yes

    - name: Configure Firewall for WebService
      firewalld:
        port: "{{ item }}"
        permanent: yes
        zone: public
        state: enabled
      loop: "{{ firewall_ports }}"

    - name: reload service httpd, in all cases
      systemd:
        name: firewalld
        state: reloaded
    
    - name: upload database
      mysql_db:
        name: ecomdb
        state: import
        target: /var/www/html/assets/db-load-script.sql

###############################################
##### The best option is use Replace Module####
   # - name: Replace IP MySQL database
   #   shell:
   #    sed -i 's/172.20.1.101/localhost/g' /var/www/html/index.php
###############################################   
    
    - name: Replace IP MySQL database
      replace:
        path: /var/www/html/index.php
        regexp: '172.20.1.101'
        replace: 'localhost'


